//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleships
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attacks
    {
        public int Attacks_ID { get; set; }
        public string Coordinate { get; set; }
        public bool Hit { get; set; }
        public int Game_Attack { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
