//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleships
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameShipConfig
    {
        public int GSC_ID { get; set; }
        public string GSC_Coordinate { get; set; }
        public string PlayerFK { get; set; }
        public int GameFK { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Players Players { get; set; }
    }
}
